remote_theme: "mmistakes/minimal-mistakes" 

locale: "ja"
title: "title"
title_separator: "|"


url: "" # write your site url
repository: "" # write your jekyll repository

author:
    avatar: "/assets/images/profile.png"
    name: "John Doe"
    bio: "This is bio"
    location: "Japan"
    twitter: "twitter"
    
paginate: 7
paginate_path: "/page:num/"

include: ["_pages"]

defaults:
    - scope:
        path: ""
        type: posts
      values:
        layout: single
        author_profile: true
        read_time: false
        comments: false
        share: true
        related: true
    - scope:
        path: ""
        type: pages
      values:
        layout: single
        author_profile: false
        read_time: false
        comments: false
        share: false
        related: false

search: true

exclude:
    - vendor
    - .bundle
    - Gemfile

plugins:
    - jekyll-include-cache
    - jekyll-remote-theme
    - jekyll-paginate
    - jekyll-feed
    - jemoji

